[versions]
#APP
sdk = "34"
minSdk = "29"
versionCode = "1"
versionName = "1.0"

#GRADLE
androidGradlePlugin = "8.2.1"

#DEPENDENCIES
ktx = "1.9.0"
kotlin = "1.7.20"
hilt = "2.44"
room = "2.4.0"
camerax = "1.3.1"
navigation-compose = "2.6.0"
navigation-compose-hilt = "1.0.0"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
#HILT
android-hilt = { group = "com.google.dagger", name= "hilt-android", version.ref = "hilt" }
android-hiltKapt = { group = "com.google.dagger", name= "hilt-android-compiler", version.ref = "hilt" }
#ROOM
android-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
android-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
android-roomKapt = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
#CAMERAX
androidx-camera-camera2  = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
androidx-camera-lifecycle  = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
androidx-camera-view  = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }
#COMPOSE
androidx-compose-navigation  = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-compose-hiltNavigation  = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "navigation-compose-hilt" }
androidx-compose-ui  = { group = "androidx.compose.ui", name = "ui", version.ref = "navigation-compose" }




#implementation 'androidx.compose.ui:ui'
#implementation 'androidx.compose.ui:ui-graphics'
#implementation 'androidx.compose.ui:ui-tooling-preview'
#implementation 'androidx.compose.material3:material3'


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
android-kapt = {id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

